MySql Templates
Azure/azure-webjobs-sdk-templates pull request #1549
Opened 2024-07-22 06:07 UTC by guptaheena

Adding templates

2024-07-31 04:31 UTC, ALEXIS007891076 approved these changes

2024-08-27 16:36 UTC, soninaren requested changes

2024-08-27 16:36 UTC, soninaren commented on Functions.Templates/Templates/MySqlInputBinding-CSharp-Isolated/.template.config/template.json
> +            "reference": "Microsoft.Azure.Functions.Worker.Extensions.MySql", "version": "0.0.000",
I don't see this published yet? This would need to be published before we could include the template in the deployment package.

2024-08-27 16:36 UTC, soninaren commented on Build/PackageFiles/Dotnet_precompiled/ItemTemplates-Isolated_NetFx_v4.x.nuspec
> +    <file src="..\..\..\Functions.Templates\Templates\MySqlInputBinding-CSharp-Isolated\**" target="content\MySqlInputBinding-CSharp-Isolated" />
Are you your templates compatible with NET framework? If not can you revert the changes to this file.

2024-08-27 16:36 UTC, soninaren commented on Build/PackageFiles/Dotnet_precompiled/ItemTemplates_v3.x.nuspec
> +    <file src="..\..\..\Functions.Templates\Templates\MySqlInputBinding-CSharp\**" target="content\MySqlInputBinding-CSharp" exclude="**\*.csx;**\*.md;**\*.dat;**\function.json;**\metadata.json" />
V3 is deprecated. As such we do not release templates for functions runtime v3. Can you revert changes to these files.

2024-08-27 16:36 UTC, soninaren commented on Build/PackageFiles/ExtensionBundle/ExtensionBundlePreviewTemplates-3.x.nuspec
> +    <file src="..\..\..\Functions.Templates\templates\MySqlInputBinding-Python\*.*" target="Templates\MySqlInputBinding-Python" />
We would be adding the extension to bundle v4 preview only. Please revert changes to this file as well.

2024-08-27 16:36 UTC, soninaren commented on Build/PackageFiles/ExtensionBundle/ExtensionBundleTemplates-4.x.nuspec
> +    <file src="..\..\..\Functions.Templates\templates\MySqlOutputBinding-PowerShell\**" target="Templates\MySqlOutputBinding-PowerShell" />
Please revert the changes to this file as well. At this point we are only releasing the templates to v4 preview bundle.

2024-08-27 16:36 UTC, soninaren commented on Build/PackageFiles/Dotnet_precompiled/ItemTemplates-Isolated_NetCore_v4.x.nuspec
> +    <file src="..\..\..\Functions.Templates\Templates\MySqlInputBinding-CSharp-Isolated\**" target="content\MySqlInputBinding-CSharp-Isolated" />
Can you revert the changes to all the `.nuspec` files until the package is published?

2024-08-27 16:36 UTC, soninaren commented on Build/PackageFiles/Dotnet_precompiled/ItemTemplates-Isolated_v4.x.nuspec
> +    <file src="..\..\..\Functions.Templates\Templates\MySqlInputBinding-CSharp-Isolated\**" target="content\MySqlInputBinding-CSharp-Isolated" />
As mentioned above, we would need to revert changes to this file until the package is published.

2024-08-27 16:36 UTC, soninaren commented on Build/PackageFiles/Dotnet_precompiled/ItemTemplates_v4.x.nuspec
> +    <file src="..\..\..\Functions.Templates\Templates\MySqlInputBinding-CSharp\**" target="content\MySqlInputBinding-CSharp" exclude="**\*.csx;**\*.md;**\*.dat;**\function.json;**\metadata.json" />
Revert please.

2024-08-27 16:36 UTC, soninaren commented on Build/PackageFiles/ExtensionBundle/ExtensionBundlePreviewTemplates-4.x.nuspec
> +    <file src="..\..\..\Functions.Templates\templates\MySqlInputBinding-Typescript\**" target="Templates\MySqlInputBinding-Typescript" />
Revert this one too.

2024-09-18 04:55 UTC, guptaheena commented on Build/PackageFiles/Dotnet_precompiled/ItemTemplates-Isolated_v4.x.nuspec
> +    <file src="..\..\..\Functions.Templates\Templates\MySqlInputBinding-CSharp-Isolated\**" target="content\MySqlInputBinding-CSharp-Isolated" />
package is published

2024-09-18 09:50 UTC, soninaren approved these changes

2024-09-18 09:50 UTC, merged